exclude: 'docs|node_modules|.git|.tox'
default_stages: [commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
        name: Check for files larger than 5 MB
        args: [ "--maxkb=5120" ]
      - id: end-of-file-fixer
        name: Check for a blank line at the end of scripts (auto-fixes)
      - id: trailing-whitespace
        name: Check for trailing whitespaces (auto-fixes)

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort - Sort Python imports (auto-fixes)
        args: [ "--profile", "black", "--filter-files" ]
        exclude: __init__.py

  - repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
      - id: black
        name: black - consistent Python code formatting (auto-fixes)
        language_version: python
        exclude: venv/

  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake --remove-all-unused-imports --ignore-init-module-imports -i --recursive .
        language: system
        pass_filenames: false
        exclude: .git|__pycache__|venv/|__init__.py|versions

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.0.3
    hooks:
      - id: detect-secrets
        name: detect-secrets - Detect secrets in staged code
        args: [ "--baseline", ".secrets.baseline" ]
        exclude: .*/tests/.*