version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - LOG_FILE=/var/log/app.log
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/log/:/var/log/

    networks:
      - dokploy-network


networks:
  dokploy-network:
    external: true
