version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - database
      - redis
    env_file:
      - src/.env

  database:
    image: postgres:16.2-alpine
    ports:
      - "5432:5432"
    env_file:
      - src/.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.5-alpine
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    depends_on:
      - redis
      - database
    command: >
      bash -c "poetry run celery -A core.tasks.celery worker --loglevel=info"
    env_file:
      - src/.env

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat
    depends_on:
      - redis
      - database
    command: >
      bash -c "poetry run celery -A core.tasks.celery beat --loglevel=info"
    env_file:
      - src/.env
    volumes:
      - ./celery_beat_data:/celerybeat-schedule
