services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"

  db:
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    env_file: .pg-env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
