"""empty message

Revision ID: 3abae26e5526
Revises: c73349e2780d
Create Date: 2025-08-06 17:47:03.620557

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3abae26e5526"
down_revision: Union[str, None] = "c73349e2780d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("answers_question_id_fkey"), "answers", type_="foreignkey")
    op.create_foreign_key(
        None, "answers", "questions", ["question_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "answers", type_="foreignkey")
    op.create_foreign_key(
        op.f("answers_question_id_fkey"),
        "answers",
        "questions",
        ["question_id"],
        ["id"],
    )
    # ### end Alembic commands ###
