"""empty message

Revision ID: 4bdc5110dce8
Revises: 888ebd2f62d8
Create Date: 2025-07-18 04:10:25.308467

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4bdc5110dce8"
down_revision: Union[str, None] = "888ebd2f62d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("group_members_user_id_fkey"), "group_members", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("group_members_group_id_fkey"), "group_members", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "group_members", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "group_members", "groups", ["group_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "group_members", type_="foreignkey")
    op.drop_constraint(None, "group_members", type_="foreignkey")
    op.create_foreign_key(
        op.f("group_members_group_id_fkey"),
        "group_members",
        "groups",
        ["group_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("group_members_user_id_fkey"),
        "group_members",
        "users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
