"""empty message

Revision ID: 888ebd2f62d8
Revises: c234d775df92
Create Date: 2025-07-18 04:07:53.086183

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "888ebd2f62d8"
down_revision: Union[str, None] = "c234d775df92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
