"""empty message

Revision ID: 921b4df66b28
Revises: 3abae26e5526
Create Date: 2025-08-06 18:05:51.972483

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "921b4df66b28"
down_revision: Union[str, None] = "3abae26e5526"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("answers_question_id_fkey"), "answers", type_="foreignkey")
    op.create_foreign_key(None, "answers", "questions", ["question_id"], ["id"])
    op.drop_constraint(
        op.f("passed_choice_answers_question_id_fkey"),
        "passed_choice_answers",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "passed_choice_answers",
        "questions",
        ["question_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("passed_text_answers_question_id_fkey"),
        "passed_text_answers",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "passed_text_answers",
        "text_questions",
        ["question_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "passed_text_answers", type_="foreignkey")
    op.create_foreign_key(
        op.f("passed_text_answers_question_id_fkey"),
        "passed_text_answers",
        "text_questions",
        ["question_id"],
        ["id"],
    )
    op.drop_constraint(None, "passed_choice_answers", type_="foreignkey")
    op.create_foreign_key(
        op.f("passed_choice_answers_question_id_fkey"),
        "passed_choice_answers",
        "questions",
        ["question_id"],
        ["id"],
    )
    op.drop_constraint(None, "answers", type_="foreignkey")
    op.create_foreign_key(
        op.f("answers_question_id_fkey"),
        "answers",
        "questions",
        ["question_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
