"""empty message

Revision ID: c73349e2780d
Revises: 4bdc5110dce8
Create Date: 2025-07-22 11:17:20.200659

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c73349e2780d"
down_revision: Union[str, None] = "4bdc5110dce8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("group_lectures_lecture_id_fkey"), "group_lectures", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("group_lectures_group_id_fkey"), "group_lectures", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "group_lectures", "lectures", ["lecture_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "group_lectures", "groups", ["group_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "group_lectures", type_="foreignkey")
    op.drop_constraint(None, "group_lectures", type_="foreignkey")
    op.create_foreign_key(
        op.f("group_lectures_group_id_fkey"),
        "group_lectures",
        "groups",
        ["group_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("group_lectures_lecture_id_fkey"),
        "group_lectures",
        "lectures",
        ["lecture_id"],
        ["id"],
    )
    # ### end Alembic commands ###
