"""empty message

Revision ID: 004e9db99f2a
Revises: 09be11dc1bc2
Create Date: 2024-11-19 14:52:16.696519

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "004e9db99f2a"
down_revision: Union[str, None] = "09be11dc1bc2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
