"""empty message

Revision ID: 00c9ddd8b513
Revises: d08628740bc1
Create Date: 2024-11-17 12:13:08.869306

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "00c9ddd8b513"
down_revision: Union[str, None] = "d08628740bc1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
