"""empty message

Revision ID: 0106c0dc9ef0
Revises: cc3f73b592f5
Create Date: 2024-11-18 21:12:57.224491

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "0106c0dc9ef0"
down_revision: Union[str, None] = "cc3f73b592f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
