"""empty message

Revision ID: 030974aa08a9
Revises: 2d17bff82dc0
Create Date: 2025-02-10 15:27:17.107562

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "030974aa08a9"
down_revision: Union[str, None] = "2d17bff82dc0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lectures", sa.Column("text", sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lectures", "text")
    # ### end Alembic commands ###
