"""empty message

Revision ID: 07ee99cc62bc
Revises: 84e2b74de5f5
Create Date: 2024-12-14 18:53:23.873759

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "07ee99cc62bc"
down_revision: Union[str, None] = "84e2b74de5f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
