"""empty message

Revision ID: 08b933a8878b
Revises: 698ec66149a6
Create Date: 2024-11-18 21:49:01.947142

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "08b933a8878b"
down_revision: Union[str, None] = "698ec66149a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
