"""empty message

Revision ID: 09be11dc1bc2
Revises: f189a0bde2be
Create Date: 2024-11-19 12:49:42.307922

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "09be11dc1bc2"
down_revision: Union[str, None] = "f189a0bde2be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
