"""empty message

Revision ID: 0a3e588d0831
Revises: 7b6aea0b2e26
Create Date: 2024-12-17 19:56:58.853945

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "0a3e588d0831"
down_revision: Union[str, None] = "7b6aea0b2e26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
