"""empty message

Revision ID: 0a77acf7b77e
Revises: 6095fb2c00b7
Create Date: 2025-06-25 01:59:34.913427

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "0a77acf7b77e"
down_revision: Union[str, None] = "6095fb2c00b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
