"""empty message

Revision ID: 0c4c355d1850
Revises: 377a0ffd2092
Create Date: 2025-02-16 17:58:00.769017

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c4c355d1850"
down_revision: Union[str, None] = "377a0ffd2092"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "passedanswers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("exam_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("selected_answer_id", sa.Integer(), nullable=True),
        sa.Column("is_correct", sa.BOOLEAN(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["selected_answer_id"],
            ["answers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_passedanswers_id"), "passedanswers", ["id"], unique=False)
    op.drop_index("ix_passedanswerss_id", table_name="passedanswerss")
    op.drop_table("passedanswerss")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "passedanswerss",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("exam_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("question_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "selected_answer_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("is_correct", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exam_id"], ["exams.id"], name="passedanswerss_exam_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["question_id"], ["questions.id"], name="passedanswerss_question_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["selected_answer_id"],
            ["answers.id"],
            name="passedanswerss_selected_answer_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="passedanswerss_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="passedanswerss_pkey"),
    )
    op.create_index("ix_passedanswerss_id", "passedanswerss", ["id"], unique=False)
    op.drop_index(op.f("ix_passedanswers_id"), table_name="passedanswers")
    op.drop_table("passedanswers")
    # ### end Alembic commands ###
