"""empty message

Revision ID: 0ec78469acf5
Revises: 3ff433b5170d
Create Date: 2025-01-03 17:35:54.053748

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "0ec78469acf5"
down_revision: Union[str, None] = "3ff433b5170d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
