"""empty message

Revision ID: 17a996b23b36
Revises: 037672601fc8
Create Date: 2024-11-13 20:49:32.122111

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "17a996b23b36"
down_revision: Union[str, None] = "037672601fc8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sa.String(), nullable=False))
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("hashed_password", sa.VARCHAR(), nullable=False))
    op.drop_column("users", "password")
    # ### end Alembic commands ###
