"""empty message

Revision ID: 1f75c1ab50cb
Revises: 43f1fa2c8b38
Create Date: 2024-12-27 22:57:26.198647

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "1f75c1ab50cb"
down_revision: Union[str, None] = "43f1fa2c8b38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
