"""empty message

Revision ID: 1f86aee77bc1
Revises: 5292badc6cde
Create Date: 2025-01-01 16:06:30.232649

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f86aee77bc1"
down_revision: Union[str, None] = "5292badc6cde"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "exams",
        "start_time",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "exams",
        "end_time",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.TIMESTAMP(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "exams",
        "end_time",
        existing_type=sa.TIMESTAMP(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "exams",
        "start_time",
        existing_type=sa.TIMESTAMP(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
