"""empty message

Revision ID: 2bc67b85e33e
Revises: c64c74c2928f
Create Date: 2025-05-09 23:02:49.940267

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "2bc67b85e33e"
down_revision: Union[str, None] = "c64c74c2928f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
