"""empty message

Revision ID: 312d6f0ac59e
Revises: a85c62370b23
Create Date: 2024-11-17 12:06:14.847262

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "312d6f0ac59e"
down_revision: Union[str, None] = "a85c62370b23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
