"""empty message

Revision ID: 346b98f13eee
Revises: 3e97f7da9ff6
Create Date: 2024-12-15 16:44:36.770312

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "346b98f13eee"
down_revision: Union[str, None] = "3e97f7da9ff6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
