"""empty message

Revision ID: 3776da73fe13
Revises: bd1e900497e9
Create Date: 2025-03-08 18:47:34.362352

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "3776da73fe13"
down_revision: Union[str, None] = "bd1e900497e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
