"""empty message

Revision ID: 38f30e357dfd
Revises: 90a9e0875e82
Create Date: 2025-01-02 19:28:57.060006

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "38f30e357dfd"
down_revision: Union[str, None] = "90a9e0875e82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
