"""empty message

Revision ID: 3b659a4bae12
Revises: e501dcb4c5e5
Create Date: 2024-12-17 17:58:58.024454

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "3b659a4bae12"
down_revision: Union[str, None] = "e501dcb4c5e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
