"""empty message

Revision ID: 3bb1920e7ed1
Revises: 1f8aef4c27a6
Create Date: 2024-11-15 13:35:41.414670

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "3bb1920e7ed1"
down_revision: Union[str, None] = "1f8aef4c27a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
