"""empty message

Revision ID: 3ce9c649847f
Revises: 58dee04afb6a
Create Date: 2025-02-19 22:08:32.031240

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "3ce9c649847f"
down_revision: Union[str, None] = "58dee04afb6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
