"""empty message

Revision ID: 3e74f2896743
Revises: 3ce9c649847f
Create Date: 2025-02-19 22:10:23.342271

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "3e74f2896743"
down_revision: Union[str, None] = "3ce9c649847f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
