"""empty message

Revision ID: 3e97f7da9ff6
Revises: 6186f9371ec1
Create Date: 2024-12-14 23:19:30.062501

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "3e97f7da9ff6"
down_revision: Union[str, None] = "6186f9371ec1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
