"""empty message

Revision ID: 3ff433b5170d
Revises: 8863dd8e3423
Create Date: 2025-01-02 22:46:23.732109

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ff433b5170d"
down_revision: Union[str, None] = "8863dd8e3423"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("questions", sa.Column("order", mysql.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "order")
    # ### end Alembic commands ###
