"""empty message

Revision ID: 41185964d6aa
Revises: 88844d546613
Create Date: 2025-01-05 16:01:15.141464

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41185964d6aa"
down_revision: Union[str, None] = "88844d546613"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exams",
        sa.Column(
            "is_started", sa.BOOLEAN(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("exams", "is_started")
    # ### end Alembic commands ###
