"""empty message

Revision ID: 412c2d68d441
Revises: 4c5bfa75f580
Create Date: 2025-01-01 16:30:35.050868

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "412c2d68d441"
down_revision: Union[str, None] = "4c5bfa75f580"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
