"""empty message

Revision ID: 48867c6e9d41
Revises: 6a32662c44af
Create Date: 2025-05-07 21:20:14.828523

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48867c6e9d41"
down_revision: Union[str, None] = "6a32662c44af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_user_message_check", "groupmessagechecks", ["user_id", "message_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_message_check", "groupmessagechecks", type_="unique")
    # ### end Alembic commands ###
