"""empty message

Revision ID: 4c5bfa75f580
Revises: 751cff1be9a7
Create Date: 2025-01-01 16:21:51.722231

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "4c5bfa75f580"
down_revision: Union[str, None] = "751cff1be9a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
