"""empty message

Revision ID: 4d34b558d324
Revises: 9b41a21e3fb9
Create Date: 2024-11-18 21:42:18.836420

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "4d34b558d324"
down_revision: Union[str, None] = "9b41a21e3fb9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
