"""empty message

Revision ID: 5292badc6cde
Revises: 85166c827b4e
Create Date: 2025-01-01 16:02:30.154223

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5292badc6cde"
down_revision: Union[str, None] = "85166c827b4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("exams", "is_ended", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("exams", "is_ended", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###
