"""empty message

Revision ID: 58dee04afb6a
Revises: c11417c1fecf
Create Date: 2025-02-19 22:02:16.629904

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql, postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "58dee04afb6a"
down_revision: Union[str, None] = "c11417c1fecf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "textquestions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exam_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("order", mysql.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_textquestions_id"), "textquestions", ["id"], unique=False)
    op.create_table(
        "passedtextanswers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("exam_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["textquestions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_passedtextanswers_id"), "passedtextanswers", ["id"], unique=False
    )
    op.create_table(
        "passedchoiceanswers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("exam_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("selected_answer_id", sa.Integer(), nullable=True),
        sa.Column("is_correct", sa.BOOLEAN(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exam_id"],
            ["exams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["selected_answer_id"],
            ["answers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_passedchoiceanswers_id"), "passedchoiceanswers", ["id"], unique=False
    )
    op.drop_index("ix_passedanswers_id", table_name="passedanswers")
    op.drop_table("passedanswers")
    op.alter_column("examresults", "score", existing_type=sa.INTEGER(), nullable=True)
    op.add_column("exams", sa.Column("is_advanced_exam", sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("exams", "is_advanced_exam")
    op.alter_column("examresults", "score", existing_type=sa.INTEGER(), nullable=False)
    op.create_table(
        "passedanswers",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("exam_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("question_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "selected_answer_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("is_correct", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exam_id"], ["exams.id"], name="passedanswers_exam_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["question_id"], ["questions.id"], name="passedanswers_question_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["selected_answer_id"],
            ["answers.id"],
            name="passedanswers_selected_answer_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="passedanswers_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="passedanswers_pkey"),
    )
    op.create_index("ix_passedanswers_id", "passedanswers", ["id"], unique=False)
    op.drop_index(op.f("ix_passedchoiceanswers_id"), table_name="passedchoiceanswers")
    op.drop_table("passedchoiceanswers")
    op.drop_index(op.f("ix_passedtextanswers_id"), table_name="passedtextanswers")
    op.drop_table("passedtextanswers")
    op.drop_index(op.f("ix_textquestions_id"), table_name="textquestions")
    op.drop_table("textquestions")
    # ### end Alembic commands ###
