"""empty message

Revision ID: 5b3c1901c53b
Revises: 4680403e2f14
Create Date: 2025-01-01 15:59:31.500946

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "5b3c1901c53b"
down_revision: Union[str, None] = "4680403e2f14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
