"""empty message

Revision ID: 6095fb2c00b7
Revises: 889247e87463
Create Date: 2025-06-02 13:25:01.955888

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6095fb2c00b7"
down_revision: Union[str, None] = "889247e87463"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("newss", "time_to_read", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("newss", "time_to_read", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
