"""empty message

Revision ID: 6186f9371ec1
Revises: 07ee99cc62bc
Create Date: 2024-12-14 18:55:00.943859

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "6186f9371ec1"
down_revision: Union[str, None] = "07ee99cc62bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
