"""empty message

Revision ID: 642c89498431
Revises: e534dcbf96f9
Create Date: 2024-11-04 22:27:47.093768

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "642c89498431"
down_revision: Union[str, None] = "e534dcbf96f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
