"""empty message

Revision ID: 65b42a557714
Revises: e2a28b0085a0
Create Date: 2024-11-18 21:07:10.854334

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "65b42a557714"
down_revision: Union[str, None] = "e2a28b0085a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
