"""empty message

Revision ID: 66e6fee57f29
Revises: b9f9cae84ee5
Create Date: 2024-12-10 23:02:13.086577

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "66e6fee57f29"
down_revision: Union[str, None] = "b9f9cae84ee5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "room_members",
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["personalrooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("room_id", "user_id"),
    )
    op.drop_table("room_participants")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "room_participants",
        sa.Column("room_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"], ["personalrooms.id"], name="room_participants_room_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="room_participants_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("room_id", "user_id", name="room_participants_pkey"),
    )
    op.drop_table("room_members")
    # ### end Alembic commands ###
