"""empty message

Revision ID: 67f80661d1a4
Revises: 3e74f2896743
Create Date: 2025-02-19 22:11:16.176071

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "67f80661d1a4"
down_revision: Union[str, None] = "3e74f2896743"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
