"""empty message

Revision ID: 689b4cda3dce
Revises: 65b42a557714
Create Date: 2024-11-18 21:09:55.202156

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "689b4cda3dce"
down_revision: Union[str, None] = "65b42a557714"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
