"""empty message

Revision ID: 698ec66149a6
Revises: 4d34b558d324
Create Date: 2024-11-18 21:47:44.616978

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "698ec66149a6"
down_revision: Union[str, None] = "4d34b558d324"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
