"""empty message

Revision ID: 6a32662c44af
Revises: d00b524818a9
Create Date: 2025-05-06 17:01:41.014659

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "6a32662c44af"
down_revision: Union[str, None] = "d00b524818a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
