"""empty message

Revision ID: 6ff923b9734c
Revises: fe90e9de8c94
Create Date: 2025-01-01 19:57:34.504398

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "6ff923b9734c"
down_revision: Union[str, None] = "fe90e9de8c94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
