"""empty message

Revision ID: 751cff1be9a7
Revises: f717ace64a77
Create Date: 2025-01-01 16:20:02.608203

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "751cff1be9a7"
down_revision: Union[str, None] = "f717ace64a77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("exams", "is_ended", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("exams", "is_ended", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
