"""empty message

Revision ID: 76d16e428f5a
Revises: 7d6f047b7e21
Create Date: 2025-04-30 16:47:48.246452

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "76d16e428f5a"
down_revision: Union[str, None] = "7d6f047b7e21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
