"""empty message

Revision ID: 7b6aea0b2e26
Revises: 3b659a4bae12
Create Date: 2024-12-17 18:01:54.182748

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b6aea0b2e26"
down_revision: Union[str, None] = "3b659a4bae12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("lectures", "file", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("lectures", "file", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
