"""empty message

Revision ID: 7d6f047b7e21
Revises: bca7baf846de
Create Date: 2025-04-30 16:47:08.448001

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "7d6f047b7e21"
down_revision: Union[str, None] = "bca7baf846de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
