"""empty message

Revision ID: 7f3f93bd0865
Revises: b2f1585a2acf
Create Date: 2025-01-04 21:43:51.871088

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "7f3f93bd0865"
down_revision: Union[str, None] = "b2f1585a2acf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
