"""empty message

Revision ID: 7f86a13e71a8
Revises: f24541c842ce
Create Date: 2024-12-25 00:04:10.317427

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "7f86a13e71a8"
down_revision: Union[str, None] = "f24541c842ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
