"""empty message

Revision ID: 8098c26d19f7
Revises: b8e492281fb1
Create Date: 2025-01-01 19:09:58.484070

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "8098c26d19f7"
down_revision: Union[str, None] = "b8e492281fb1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
