"""empty message

Revision ID: 85166c827b4e
Revises: 996123641768
Create Date: 2025-01-01 16:01:52.311121

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "85166c827b4e"
down_revision: Union[str, None] = "996123641768"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
