"""empty message

Revision ID: 8863dd8e3423
Revises: 0a93cce4c47d
Create Date: 2025-01-02 22:31:45.691329

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8863dd8e3423"
down_revision: Union[str, None] = "0a93cce4c47d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "order")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questions",
        sa.Column("order", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
