"""empty message

Revision ID: 88844d546613
Revises: 7a206cebac59
Create Date: 2025-01-04 22:33:18.326267

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "88844d546613"
down_revision: Union[str, None] = "7a206cebac59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
