"""empty message

Revision ID: 889247e87463
Revises: d466b2c74128
Create Date: 2025-06-02 13:22:54.517196

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "889247e87463"
down_revision: Union[str, None] = "d466b2c74128"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("newss", sa.Column("time_to_read", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("newss", "time_to_read")
    # ### end Alembic commands ###
