"""empty message

Revision ID: 897a430a7ca9
Revises: 0ec78469acf5
Create Date: 2025-01-03 17:37:59.328892

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "897a430a7ca9"
down_revision: Union[str, None] = "0ec78469acf5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
