"""empty message

Revision ID: 8ab06ce93ba3
Revises: 65276e62f3d8
Create Date: 2024-11-17 12:03:29.740042

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "8ab06ce93ba3"
down_revision: Union[str, None] = "65276e62f3d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
