"""empty message

Revision ID: 9b41a21e3fb9
Revises: 0106c0dc9ef0
Create Date: 2024-11-18 21:39:59.114532

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "9b41a21e3fb9"
down_revision: Union[str, None] = "0106c0dc9ef0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
