"""empty message

Revision ID: a2e1a57e3b09
Revises: 67f80661d1a4
Create Date: 2025-02-20 17:31:43.917878

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "a2e1a57e3b09"
down_revision: Union[str, None] = "67f80661d1a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
