"""empty message

Revision ID: a3927361506c
Revises: 56a39b10fed7
Create Date: 2025-05-03 20:11:42.288209

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3927361506c"
down_revision: Union[str, None] = "56a39b10fed7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "privatemessages",
        sa.Column(
            "is_readed", sa.BOOLEAN(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("privatemessages", "is_readed")
    # ### end Alembic commands ###
