"""empty message

Revision ID: a85c62370b23
Revises: 8ab06ce93ba3
Create Date: 2024-11-17 12:05:35.370214

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "a85c62370b23"
down_revision: Union[str, None] = "8ab06ce93ba3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
