"""empty message

Revision ID: b2f1585a2acf
Revises: 897a430a7ca9
Create Date: 2025-01-04 21:43:26.446394

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "b2f1585a2acf"
down_revision: Union[str, None] = "897a430a7ca9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
