"""empty message

Revision ID: b8e492281fb1
Revises: 412c2d68d441
Create Date: 2025-01-01 16:30:51.101529

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "b8e492281fb1"
down_revision: Union[str, None] = "412c2d68d441"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
