"""empty message

Revision ID: bca7baf846de
Revises: cb0920de8708
Create Date: 2025-04-26 17:39:34.276275

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "bca7baf846de"
down_revision: Union[str, None] = "cb0920de8708"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
