"""empty message

Revision ID: bd1e900497e9
Revises:
Create Date: 2025-02-23 14:42:15.368947

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd1e900497e9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "exams", "is_advanced_exam", existing_type=sa.BOOLEAN(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "exams", "is_advanced_exam", existing_type=sa.BOOLEAN(), nullable=False
    )
    # ### end Alembic commands ###
