"""empty message

Revision ID: c0890c7ae3ac
Revises: 2bc67b85e33e
Create Date: 2025-05-30 13:45:53.722117

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0890c7ae3ac"
down_revision: Union[str, None] = "2bc67b85e33e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "newss",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.VARCHAR(length=255), nullable=False),
        sa.Column("text", sa.TEXT(), nullable=False),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_newss_id"), "newss", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_newss_id"), table_name="newss")
    op.drop_table("newss")
    # ### end Alembic commands ###
