"""empty message

Revision ID: c11417c1fecf
Revises: 0c4c355d1850
Create Date: 2025-02-16 17:59:38.093585

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "c11417c1fecf"
down_revision: Union[str, None] = "0c4c355d1850"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
