"""empty message

Revision ID: c64c74c2928f
Revises: 48867c6e9d41
Create Date: 2025-05-09 23:01:54.954429

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "c64c74c2928f"
down_revision: Union[str, None] = "48867c6e9d41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
