"""empty message

Revision ID: ca8e386df5e0
Revises: 030974aa08a9
Create Date: 2025-02-10 15:28:53.185010

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca8e386df5e0"
down_revision: Union[str, None] = "030974aa08a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("lectures", "file", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("lectures", "file", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
