"""empty message

Revision ID: cc3f73b592f5
Revises: 689b4cda3dce
Create Date: 2024-11-18 21:12:00.675907

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "cc3f73b592f5"
down_revision: Union[str, None] = "689b4cda3dce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
