"""empty message

Revision ID: ce0303dc88f4
Revises: d4aad9ddff65
Create Date: 2025-01-01 19:17:40.544779

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "ce0303dc88f4"
down_revision: Union[str, None] = "d4aad9ddff65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
