"""empty message

Revision ID: d00b524818a9
Revises: a93bcf1623bf
Create Date: 2025-05-06 16:57:50.798666

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "d00b524818a9"
down_revision: Union[str, None] = "a93bcf1623bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
