"""empty message

Revision ID: d08628740bc1
Revises: 312d6f0ac59e
Create Date: 2024-11-17 12:06:38.592460

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "d08628740bc1"
down_revision: Union[str, None] = "312d6f0ac59e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
