"""empty message

Revision ID: d466b2c74128
Revises: c0890c7ae3ac
Create Date: 2025-06-02 12:54:54.333426

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d466b2c74128"
down_revision: Union[str, None] = "c0890c7ae3ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.add_column("newss", sa.Column("category_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "newss", "categories", ["category_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "newss", type_="foreignkey")
    op.drop_column("newss", "category_id")
    op.drop_table("categories")
    # ### end Alembic commands ###
