"""empty message

Revision ID: d4aad9ddff65
Revises: 8098c26d19f7
Create Date: 2025-01-01 19:10:47.897441

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "d4aad9ddff65"
down_revision: Union[str, None] = "8098c26d19f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
