"""empty message

Revision ID: e09713c0d0c6
Revises: 41185964d6aa
Create Date: 2025-01-07 21:07:15.345998

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "e09713c0d0c6"
down_revision: Union[str, None] = "41185964d6aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
