"""empty message

Revision ID: e2a28b0085a0
Revises: fa6beab4acae
Create Date: 2024-11-18 20:54:54.318414

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "e2a28b0085a0"
down_revision: Union[str, None] = "fa6beab4acae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
