"""empty message

Revision ID: f189a0bde2be
Revises: 08b933a8878b
Create Date: 2024-11-18 21:55:46.335991

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "f189a0bde2be"
down_revision: Union[str, None] = "08b933a8878b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
