"""empty message

Revision ID: fe90e9de8c94
Revises: ce0303dc88f4
Create Date: 2025-01-01 19:22:45.971748

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "fe90e9de8c94"
down_revision: Union[str, None] = "ce0303dc88f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
